# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70e3e18deaa14fa85dae468f37b9627b744aee3e78d8d2f1200f9dc563c2f7b469ed01e359f550e67a032f3601991be6ee1878bae6940694c16815b8d98366a5

test:
  secret_key_base: 5e3c447bd87ba6ccc3a57598908cb38a0c22583ab4d261fe557409475815dd1aaaa6b2dc30f55a542702bf7f9badf36463c3d59c96f88844baed1477c66df3da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
